#!/bin/sh

cat <<EOF > /usr/share/nginx/html/env.js
window.APP_CONFIG = {
  KEYCLOAK_URL: "${VITE_KEYCLOAK_URL}",
  KEYCLOAK_REALM: "${VITE_KEYCLOAK_REALM}",
  KEYCLOAK_CLIENT_ID: "${VITE_KEYCLOAK_LANDING_CLIENT_ID}",
  GRAFANA_DASHBOARD_URL: "${VITE_GRAFANA_DASHBOARD_URL}",
  LINK_AGENT: "${VITE_LINK_AGENT}",
  LINK_SERVICES: "${VITE_LINK_SERVICES}",
  LINK_DEV_PORTAL: "${VITE_LINK_DEV_PORTAL}",
  LINK_GRAFANA: "${VITE_LINK_GRAFANA}",
  LINK_ARGOCD: "${VITE_LINK_ARGOCD}",
  LINK_TRAEFIK: "${VITE_LINK_TRAEFIK}",
  LINK_KEYCLOAK: "${VITE_LINK_KEYCLOAK}",
  HEALTH_URL: "${VITE_HEALTH_URL}"
};
EOF
