---
# Source: arges/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: arges
  labels:
    app.kubernetes.io/name: arges
    app.kubernetes.io/instance: arges
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "dev"
    helm.sh/chart: arges-0.1.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arges
    app.kubernetes.io/instance: arges
  ports:
    - name: http
      port: 7302
      targetPort: 7302
    - name: grpc
      port: 7303
      targetPort: 7303

---
# Source: arges/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arges
  labels:
    app.kubernetes.io/name: arges
    app.kubernetes.io/instance: arges
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "dev"
    helm.sh/chart: arges-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arges
      app.kubernetes.io/instance: arges
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arges
        app.kubernetes.io/instance: arges
    spec:
      containers:
        - name: arges
          image: "arges:dev"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7302
            - name: grpc
              containerPort: 7303
          env:
            - name: ARGES_SERVER_PORT
              value: "7302"
            - name: ARGES_SERVER_GRPC_PORT
              value: "7303"
            - name: OTEL_SERVICE_NAME
              value: "arges"
            - name: OTEL_ENABLED_ARGES
              value: "false"
            - name: PROTEUS_SERVER
              value: proteus
            - name: PROTEUS_SERVER_GRPC_PORT
              value: "7276"
          readinessProbe:
            httpGet:
              path: /ready
              port: 7302
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 7302
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
