---
# Source: steropes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: steropes
  labels:
    app.kubernetes.io/name: steropes
    app.kubernetes.io/instance: steropes
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "dev"
    helm.sh/chart: steropes-0.1.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: steropes
    app.kubernetes.io/instance: steropes
  ports:
    - name: http
      port: 7300
      targetPort: 7300
    - name: grpc
      port: 7301
      targetPort: 7301

---
# Source: steropes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steropes
  labels:
    app.kubernetes.io/name: steropes
    app.kubernetes.io/instance: steropes
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "dev"
    helm.sh/chart: steropes-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: steropes
      app.kubernetes.io/instance: steropes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: steropes
        app.kubernetes.io/instance: steropes
    spec:
      containers:
        - name: steropes
          image: "steropes:dev"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7300
            - name: grpc
              containerPort: 7301
          env:
            - name: STEROPES_SERVER_PORT
              value: "7300"
            - name: STEROPES_SERVER_GRPC_PORT
              value: "7301"
            - name: OTEL_SERVICE_NAME
              value: "steropes"
            - name: OTEL_ENABLED_STEROPES
              value: "false"
          readinessProbe:
            httpGet:
              path: /ready
              port: 7300
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 7300
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 512Mi
