// Zod codegen (Stage 1.3 T4). Reads the BFF's validation-rules.yaml (contracts
// §4 — the single declarative source) and emits src/validation/generated.ts.
// This is layer 1 of the three-layer validation; never hand-edit the output.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { parse } from 'yaml'

const here = dirname(fileURLToPath(import.meta.url))
const rulesPath = resolve(here, '../../../agents/sysifos-bff/src/main/resources/validation-rules.yaml')
const outDir = resolve(here, '../src/validation')
const outPath = resolve(outDir, 'generated.ts')

const rules = parse(readFileSync(rulesPath, 'utf8'))

const DECIMAL_RE = '/^-?\\d+(\\.\\d+)?$/'

/** A single non-nested field rule → a Zod expression. */
function leaf(spec) {
  let s
  if (spec.enum) {
    s = 'z.string().min(1)' // enum value name; cross-checked against the dictionary FE-side
  } else {
    switch (spec.type) {
      case 'uuid': s = 'z.string().uuid()'; break
      case 'email': s = 'z.string().email()'; break
      case 'iso4217': s = `z.string().regex(/^[A-Z]{3}$/, 'ISO 4217 code')`; break
      case 'date': {
        s = 'z.string().min(1)'
        // `max: today` → not in the future (compared lexically on the YYYY-MM-DD prefix,
        // evaluated at validation time, not codegen time).
        if (spec.max === 'today') {
          s += `.refine((v) => v.slice(0, 10) <= new Date().toISOString().slice(0, 10), 'not_in_future')`
        }
        break
      }
      case 'bool': s = 'z.boolean()'; break
      case 'decimal': {
        s = `z.string().regex(${DECIMAL_RE}, 'decimal')`
        if (spec.gte !== undefined) s += `.refine((v) => parseFloat(v) >= ${spec.gte}, 'must be >= ${spec.gte}')`
        if (spec.ne !== undefined) s += `.refine((v) => parseFloat(v) !== ${spec.ne}, 'must not be ${spec.ne}')`
        break
      }
      default: s = 'z.string()'
    }
  }
  if (spec.max_len) s += `.max(${spec.max_len})`
  if (spec.type === undefined && !spec.enum && spec.required) s += '.min(1)'
  if (spec.default !== undefined) s += `.default(${JSON.stringify(spec.default)})`
  if (!spec.required && spec.default === undefined) s += '.optional()'
  return s
}

/** Build the object body, nesting dotted keys (e.g. price.amount → price: { amount }). */
function formObject(fields) {
  const tree = {}
  for (const [key, spec] of Object.entries(fields)) {
    const parts = key.split('.')
    let node = tree
    for (let i = 0; i < parts.length - 1; i++) {
      node[parts[i]] ??= { __nested: true }
      node = node[parts[i]]
    }
    node[parts[parts.length - 1]] = spec
  }
  return render(tree)
}

function render(node) {
  const entries = Object.entries(node).filter(([k]) => k !== '__nested')
  const lines = entries.map(([k, v]) => {
    const expr = v && v.__nested ? `z.object(${render(v)})` : leaf(v)
    return `  ${k}: ${expr},`
  })
  return `{\n${lines.join('\n')}\n}`
}

const header = `// GENERATED by scripts/gen-zod.mjs from agents/sysifos-bff/.../validation-rules.yaml.
// Do not edit — regenerate with \`npm run gen:zod\`. Layer 1 of the three-layer
// validation (Sysifos contracts §4).
import { z } from 'zod'
`

/** Object-level `.superRefine(...)` for cross-field rules (e.g. `gte_field`). */
function crossFieldRefines(fields) {
  const refines = []
  for (const [key, spec] of Object.entries(fields)) {
    if (spec.gte_field) {
      // settle_date >= trade_date, compared lexically on the YYYY-MM-DD prefix; only
      // enforced when both sides are present (the field itself may be optional).
      refines.push(
        `.superRefine((val, ctx) => {\n` +
          `  if (val.${key} && val.${spec.gte_field} && val.${key}.slice(0, 10) < val.${spec.gte_field}.slice(0, 10)) {\n` +
          `    ctx.addIssue({ code: 'custom', path: ['${key}'], message: '${key} must be >= ${spec.gte_field}' })\n` +
          `  }\n` +
          `})`,
      )
    }
  }
  return refines.join('')
}

const blocks = Object.entries(rules).map(([form, fields]) => {
  const schema = `z.object(${formObject(fields)})${crossFieldRefines(fields)}`
  return `export const ${form}Schema = ${schema}\nexport type ${form}Input = z.input<typeof ${form}Schema>\nexport type ${form}Output = z.output<typeof ${form}Schema>`
})

mkdirSync(outDir, { recursive: true })
writeFileSync(outPath, header + '\n' + blocks.join('\n\n') + '\n')
console.log(`gen-zod: wrote ${outPath} (${blocks.length} schemas)`)
