server {
    port = "7262"
    port = ${?METIS_MCP_SERVER_PORT}
    shutdownUrlPath = "/shutdown"
}

metis {
    host = "metis"
    host = ${?METIS_GRPC_HOST}
    port = "7261"
    port = ${?METIS_GRPC_PORT}
}

capabilities-mcp {
    url = ""
    url = ${?CAPABILITIES_MCP_URL}
}

telemetry {
    enabled = false
    enabled = ${?OTEL_ENABLED_METIS_MCP}
    otlp {
        endpoint = "http://localhost:4317"
        endpoint = ${?OTEL_EXPORTER_OTLP_ENDPOINT}
    }
}
