apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kantheon
resources: [../../base]
patches:
  - target: { kind: Deployment, name: kleio }
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
