package org.tatrman.kantheon.iris.protocol.render

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.tatrman.kantheon.iris.protocol.FixtureLoader
import org.tatrman.kantheon.iris.protocol.model.DocumentBuilder
import org.tatrman.kantheon.iris.protocol.redact.RedactionChain

/**
 * Renderer behaviour (S-8). Byte-equality for every case lives in
 * `GoldenCorpusSpec`; these are the rules a reader depends on, asserted directly
 * so a golden diff has a named cause.
 */
class MarkdownRendererSpec :
    StringSpec({

        fun render(case: String): String {
            val req = FixtureLoader.request(case)
            val profile = req.config.profile(req.profileName)
            val doc = RedactionChain.standard().redact(DocumentBuilder.build(req), profile)
            return MarkdownRenderer(req.config.sessionSplitThreshold).render(doc)
        }

        "H1-full document renders byte-equal to its expected.md" {
            render("H1-full") shouldBe FixtureLoader.expectedMarkdown("H1-full")
        }

        "H3-operator renders byte-equal to its expected.md, and differs from H1" {
            render("H3-operator") shouldBe FixtureLoader.expectedMarkdown("H3-operator")

            // The profile must actually change the DOCUMENT, not merely its styling:
            // operator masks SQL literals and drops the plan entirely.
            val operator = render("H3-operator")
            operator shouldContain "Literals masked by profile."
            operator shouldNotContain "### Plan"
            render("H1-full") shouldContain "### Plan"
        }

        "truncated section emits the marker in exactly the contracted format" {
            render("truncation") shouldContain "_…truncated — 42 more lines; source: service-logs_"
        }

        "folding: no <details> is emitted (Q-15 = no) — plain headings instead" {
            FixtureLoader.CASES.forEach { case ->
                val md = render(case)
                // The FE builds markdown-it with html:false and no sanitizer, so raw
                // HTML would render as escaped literal text. Headings it is.
                md shouldNotContain "<details>"
                md shouldNotContain "<summary>"
            }
            render("H1-full") shouldContain "### Overview"
        }

        "session scope over the split threshold -> index + per-turn anchors, still ONE document" {
            val md = render("session-split")

            md shouldContain "## Contents"
            md shouldContain "1. [How did gross margin move in Q3?](#turn-1)"
            md shouldContain "<a id=\"turn-13\"></a>"
            // PT-10 γ: v1 stays a single markdown document; a real multi-doc split is
            // reserved, not implemented.
            Regex("^# ", RegexOption.MULTILINE).findAll(md).count() shouldBe 1

            // Under the threshold, no index at all.
            render("H1-full") shouldNotContain "## Contents"
        }

        "receipts are rendered last, always" {
            FixtureLoader.CASES.forEach { case ->
                val md = render(case)
                val receiptsAt = md.indexOf("## Receipts")
                (receiptsAt > 0) shouldBe true
                // Nothing but the receipts table follows it.
                md.substring(receiptsAt) shouldNotContain "## Turn"
                md.trimEnd().endsWith("Generated by:** iris-bff/1.0 hartland") shouldBe true
            }
        }

        "a degraded section says so once, not twice" {
            // Regression guard: the first generated pass emitted "_unavailable — see
            // receipts_" followed by a redundant "_no content_" under every degraded
            // heading. Both lines together read as two separate failures.
            val md = render("degraded-loki")
            md shouldContain "_unavailable — see receipts_"
            md shouldNotContain "_unavailable — see receipts_\n\n_no content_"
        }
    })
