package org.tatrman.kantheon.iris.protocol.render

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.tatrman.kantheon.iris.protocol.FixtureLoader
import org.tatrman.kantheon.iris.protocol.model.DocumentBuilder
import org.tatrman.kantheon.iris.protocol.redact.RedactionChain
import org.tatrman.kantheon.protocol.v1.Section

/**
 * Renderer behaviour (S-8). Byte-equality for every case lives in
 * `GoldenCorpusSpec`; these are the rules a reader depends on, asserted directly
 * so a golden diff has a named cause.
 */
class MarkdownRendererSpec :
    StringSpec({

        fun render(case: String): String {
            val req = FixtureLoader.request(case)
            val profile = req.config.profile(req.profileName)
            val doc = RedactionChain.standard().redact(DocumentBuilder.build(req), profile)
            return MarkdownRenderer(req.config.sessionSplitThreshold).render(doc)
        }

        "H1-full document renders byte-equal to its expected.md" {
            render("H1-full") shouldBe FixtureLoader.expectedMarkdown("H1-full")
        }

        "H3-operator renders byte-equal to its expected.md, and differs from H1" {
            render("H3-operator") shouldBe FixtureLoader.expectedMarkdown("H3-operator")

            // The profile must actually change the DOCUMENT, not merely its styling:
            // operator masks SQL literals and drops the plan entirely.
            val operator = render("H3-operator")
            operator shouldContain "Literals masked by profile."
            operator shouldNotContain "### Plan"
            render("H1-full") shouldContain "### Plan"
        }

        "truncated section emits the marker in exactly the contracted format" {
            render("truncation") shouldContain "_…truncated — 42 more lines; source: service-logs_"
        }

        "folding: no <details> is emitted (Q-15 = no) — plain headings instead" {
            FixtureLoader.CASES.forEach { case ->
                val md = render(case)
                // The FE builds markdown-it with html:false and no sanitizer, so raw
                // HTML would render as escaped literal text. Headings it is.
                md shouldNotContain "<details>"
                md shouldNotContain "<summary>"
            }
            render("H1-full") shouldContain "### Overview"
        }

        "session scope over the split threshold -> index + per-turn anchors, still ONE document" {
            val md = render("session-split")

            md shouldContain "## Contents"
            md shouldContain "1. [How did gross margin move in Q3?](#turn-1)"
            md shouldContain "<a id=\"turn-13\"></a>"
            // PT-10 γ: v1 stays a single markdown document; a real multi-doc split is
            // reserved, not implemented.
            Regex("^# ", RegexOption.MULTILINE).findAll(md).count() shouldBe 1

            // Under the threshold, no index at all.
            render("H1-full") shouldNotContain "## Contents"
        }

        "receipts are rendered last, always" {
            FixtureLoader.CASES.forEach { case ->
                val md = render(case)
                val receiptsAt = md.indexOf("## Receipts")
                (receiptsAt > 0) shouldBe true
                // Nothing but the receipts table follows it.
                md.substring(receiptsAt) shouldNotContain "## Turn"
                md.trimEnd().endsWith("Generated by:** iris-bff/1.0 hartland") shouldBe true
            }
        }

        // ---- structural integrity: the document may not be forged from inside ----

        /**
         * Headings that markdown actually renders — i.e. outside every fenced block.
         * Walks the fences the way CommonMark does: a run of >= 3 backticks opens, and
         * only a run at least as long closes. Counting raw `## …` lines would count the
         * *quoted* ones too, which is precisely what the fence is there to neutralise.
         */
        fun structuralHeadings(md: String): List<String> {
            var fence: Int? = null
            val out = mutableListOf<String>()
            md.lineSequence().forEach { line ->
                val run = line.takeWhile { it == '`' }.length
                when {
                    fence == null && run >= 3 -> fence = run
                    fence != null && run >= fence!! && line.trim().all { it == '`' } -> fence = null
                    fence == null && line.startsWith("#") -> out += line
                }
            }
            return out
        }

        /**
         * The content of the fenced block that follows [marker], read the way
         * CommonMark reads it: the opening run sets the width, and the block ends at
         * the first line whose run is at least that wide. So this returns what a
         * *renderer* would show — which is the point. If the body could close its own
         * fence, what comes back is a prefix of the body and the rest has escaped into
         * the document.
         */
        fun fencedBlockAfter(
            md: String,
            marker: String,
        ): String {
            val lines = md.lines()
            val start = lines.indexOfFirst { it == marker }
            require(start >= 0) { "marker not found: $marker" }
            val openAt = (start + 1 until lines.size).first { lines[it].startsWith("```") }
            val width = lines[openAt].takeWhile { it == '`' }.length
            val body = mutableListOf<String>()
            for (i in openAt + 1 until lines.size) {
                val line = lines[i]
                val run = line.takeWhile { it == '`' }.length
                if (run >= width && line.trim().all { it == '`' }) return body.joinToString("\n")
                body += line
            }
            error("unterminated fence after $marker")
        }

        "content cannot close its own fence and continue in markdown" {
            // review-079 R2. A fixed ``` fence let any body the document does not
            // control — user-supplied SQL literals, log lines, prompt bodies — end the
            // block early and keep going as real markdown. The `injection` fixture
            // carries a fence plus a forged receipts table in five different fields.
            val req = FixtureLoader.request("injection")
            val profile = req.config.profile(req.profileName)
            val doc = RedactionChain.standard().redact(DocumentBuilder.build(req), profile)
            val md = MarkdownRenderer(req.config.sessionSplitThreshold).render(doc)

            // What the reader sees inside the fence is the WHOLE body — not a prefix
            // ending where the body's own backticks happened to fall. This is the
            // assertion that bites: with a fixed ``` fence it comes back truncated at
            // the hostile fence and the rest of the body has become live markdown.
            val message =
                doc.turnsList
                    .flatMap { it.sectionsList }
                    .first { it.payloadCase == Section.PayloadCase.LLM_CALLS }
                    .llmCalls
                    .getCalls(0)
                    .getMessages(0)
                    .content
            fencedBlockAfter(md, "_user:_") shouldBe message.trimEnd('\n')

            // The same for the SQL, whose literal carries the forged table.
            fencedBlockAfter(md, "### SQL") shouldBe
                doc.turnsList
                    .flatMap { it.sectionsList }
                    .first { it.payloadCase == Section.PayloadCase.SQL }
                    .sql.sql
                    .trimEnd('\n')

            // The forged text is therefore present but quoted — nothing was silently
            // dropped, which would be its own kind of dishonesty — and the document
            // still has exactly one receipts heading of its own, last.
            md shouldContain "99 record row(s)"
            structuralHeadings(md).count { it == "## Receipts" } shouldBe 1
            structuralHeadings(md).last() shouldBe "## Receipts"
        }

        "the title is one line, whatever the question was" {
            // The title is `question.take(60)`; a multi-line question would otherwise
            // continue past the `# ` and inject markdown at line 1 of the document.
            val md = render("injection")
            md.lineSequence().first() shouldContain "# Protocol —"
            md.lineSequence().first() shouldContain "Not the real title"
            // ...as text on the title line, NOT as its own heading.
            md shouldNotContain "\n# Not the real title"
        }

        "a pipe in cell content does not reshape the table it lands in" {
            // review-079 R3. Receipt details are built from upstream exception
            // messages, so their content is not ours.
            val doc =
                DocumentBuilder
                    .build(FixtureLoader.request("injection"))
                    .toBuilder()
                    .apply {
                        receiptsBuilder.getSourcesBuilder(0).detail = "a | b | c"
                    }.build()
            val md = MarkdownRenderer().render(doc)
            // The REAL receipts row — `last`, not `first`: the injection fixture's
            // quoted table also opens with `| records |`, which is exactly the
            // confusion the fence now contains.
            val row = md.lineSequence().last { it.startsWith("| records |") }

            // Three columns, not five: the pipes are escaped, not structural.
            row.split(Regex("(?<!\\\\)\\|")).filter { it.isNotBlank() }.size shouldBe 3
            row shouldContain "a \\| b \\| c"
        }

        "a degraded section says so once, not twice" {
            // Regression guard: the first generated pass emitted "_unavailable — see
            // receipts_" followed by a redundant "_no content_" under every degraded
            // heading. Both lines together read as two separate failures.
            val md = render("degraded-loki")
            md shouldContain "_unavailable — see receipts_"
            md shouldNotContain "_unavailable — see receipts_\n\n_no content_"
        }
    })
