server {
    port = "7252"
    port = ${?CHARON_MCP_SERVER_PORT}
    shutdownUrlPath = "/shutdown"
}

charon {
    host = "charon"
    host = ${?CHARON_GRPC_HOST}
    port = "7251"
    port = ${?CHARON_GRPC_PORT}
}

capabilities-mcp {
    url = ""
    url = ${?CAPABILITIES_MCP_URL}
}

telemetry {
    enabled = false
    enabled = ${?OTEL_ENABLED_CHARON_MCP}
    otlp {
        endpoint = "http://localhost:4317"
        endpoint = ${?OTEL_EXPORTER_OTLP_ENDPOINT}
    }
}
